### ISSUE TITLE
Add option to exclude derivatives from export

### ISSUE THREAD

**Issue by timothyryanwalsh** [eprintsug/EPrintsArchivematica#4]
It is possible that not all users will want to export derivative files from EPrints, as Archivematica is capable of generating very similar access derivatives. Should this functionality be made configurable?

**Comment by photomedia** [comment]
Sure, we can add an option to exclude any derivative files:

$c->{DPExport}->{include_derivatives}=1;

Setting this to 0 would exclude anything such as thumbnail images and web accessible versions of the audio and video files.

**Comment by photomedia** [comment]
Thanks, that is relevant, but since we are not getting Archivematica to generate a DIP, we don't really need to worry about re-using derivatives.
