### ISSUE TITLE
Managing errors and checking status of exports

### ISSUE THREAD

**Issue by timothyryanwalsh** [eprintsug/EPrintsArchivematica#8]
How are problematic exports detected? How can the export status of an eprint be checked by an administrative user?

**Comment by photomedia** [comment]
We need an EPrintsArchivematica preservation management screen that will allow the administrator to browse eprints, including the last exported date, and export status (success or failure - with reason).  For example, an eprint fails the checksum rechecking prior to export  and so is not exported, or is exported with new checksum.
